### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Soundtoxin** [metroid-maniac/gba-auto-batteryless-patcher#10]
I just recently learned about this program, but I see on the releases page there are just some .exe files. Are there any plans to support other operating systems?

**Comment by metroid-maniac** [comment]
The provided build command produces a Linux executable if you have devkitARM (or probably even just ARM binutils) installed. There isn't a binary release.

**Comment by LucentW** [comment]
Reporting in that it builds fine on Linux. I'm on Void Linux and installing `cross-arm-none-eabi` is enough to have the toolchain to assemble the payload, `base-devel` for the host compiler.

**Comment by Soundtoxin** [comment]
Thanks for confirming. I'll close this then.

**Comment by LucentW** [comment]
> Thanks for confirming. I'll close this then.

Remember that depending on the distribution the packages will have different names, i.e. Ubuntu and Debian's packages are `binutils-arm-none-eabi` and `gcc-arm-none-eabi` + `build-essentials` for the host machine toolchain.
